project:
  type: website
  output-dir: docs
website:
  title: "**'Kolade Gracious**"
  favicon: favicon.ico
  back-to-top-navigation: true
  google-analytics: "G-VMYDMXZZFN"
  #reader-mode: true
  sidebar: 
    style: "docked"
  page-footer: 
    center: "Copyright 2025. Gracious OGUNKOLADE"
    background: light
  navbar:
    #right:
    tools:    
      #- icon: rss
      #  href: blog/index.xml
        #text: Blog RSS
    #  - icon: twitter
     #   href: https://twitter.com/DrealOtunba
      - icon: github
        href: https://github.com/koladegray
    #  - icon: linkedin
   #     href: https://linkedin.com/gracious-ogunkolade
     # - icon: medium
     #   href: https://medium.com/gray-commits
        
    left:
     #- href: index.qmd
     #   text: About
      - href: blogs/index.qmd
        text: Med.Comms
      - href: data/index.qmd
        text: Strategy & Analytics
      #- href: papers/index.qmd
      #  text: Papers
      #- href: journals/index.qmd
      #  text: Journal Articles
      #- href: copies/index.qmd
      #  text: Copies

format:
  html:
    theme: 
      dark: [Darkly, theme.scss] #Dark mode as default appearance
      light: Flatly
    css: theme.scss
    toc: true
    #theme: flatly Darkly
#Superhero United Sandstone Journal
editor: source


